### PR TITLE
Pass in disabled prop

### PR DESCRIPTION
**Pull request by edenh**
cc @tmcw

### CODE REVIEW

**Comment by tmcw** [comment]
Hm, can you remove the package.json bump and then do that with `npm version patch` so that it results in a git tag too?

**Comment by tmcw** [comment]
Actually this should be `1.2.0` [since it's new functionality](http://semver.org/) - so `npm version minor`

**Comment by tmcw** [comment]
Oh - also - please add this new option to the `README`

**Comment by edenh** [comment]
:+1: can you publish or add me as an author?

**Comment by tmcw** [comment]
y, done.

**Pull request merged**
